name: Deploy
on:
  push:
    branches:
      - goshujin  # 确保这是您想要触发部署的分支名称 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Install Node"
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
      - name: "Setup"
        run: yarn install
      - name: "Test"
        run: yarn test
      - name: "Deploy"
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: deploy
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
